"""init fundflow schema

Revision ID: cadadc94039f
Revises:
Create Date: 2026-10-05 01:44:22.780660

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'cadadc94039f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('webhook_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('provider_reference', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('signature', sa.String(length=128), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_events')),
    sa.UniqueConstraint('provider', 'provider_reference', 'event_type', name='uq_webhook_events_provider_ref_event')
    )
    with op.batch_alter_table('webhook_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_events_provider_reference'), ['provider_reference'], unique=False)

    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('short_description', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('raised_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('disbursed_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('is_diaspora', sa.Boolean(), nullable=False),
    sa.Column('cover_image', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_campaigns_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaigns'))
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaigns_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_campaigns_status'), ['status'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reference', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor_id_users')),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_audit_logs_campaign_id_campaigns')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)

    op.create_table('beneficiaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('beneficiary_type', sa.String(length=32), nullable=False),
    sa.Column('bank_code', sa.String(length=16), nullable=False),
    sa.Column('bank_name', sa.String(length=128), nullable=False),
    sa.Column('account_number', sa.String(length=32), nullable=False),
    sa.Column('resolved_account_name', sa.String(length=255), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('verification_status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_beneficiaries_campaign_id_campaigns')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_beneficiaries')),
    sa.UniqueConstraint('campaign_id', 'bank_code', 'account_number', name=op.f('uq_beneficiaries_campaign_id'))
    )
    with op.batch_alter_table('beneficiaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_beneficiaries_campaign_id'), ['campaign_id'], unique=False)

    op.create_table('campaign_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('kora_account_reference', sa.String(length=255), nullable=False),
    sa.Column('kora_account_number', sa.String(length=32), nullable=False),
    sa.Column('bank_name', sa.String(length=128), nullable=False),
    sa.Column('bank_code', sa.String(length=16), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_campaign_accounts_campaign_id_campaigns')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaign_accounts'))
    )
    with op.batch_alter_table('campaign_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_accounts_campaign_id'), ['campaign_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_campaign_accounts_kora_account_number'), ['kora_account_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_accounts_kora_account_reference'), ['kora_account_reference'], unique=False)

    op.create_table('campaign_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_campaign_members_campaign_id_campaigns')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_campaign_members_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaign_members')),
    sa.UniqueConstraint('campaign_id', 'user_id', name=op.f('uq_campaign_members_campaign_id'))
    )
    with op.batch_alter_table('campaign_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_members_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_members_user_id'), ['user_id'], unique=False)

    op.create_table('contributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('kora_reference', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('fee', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('contributor_id', sa.Integer(), nullable=True),
    sa.Column('contributor_name', sa.String(length=255), nullable=True),
    sa.Column('anonymous', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('payment_method', sa.String(length=32), nullable=False),
    sa.Column('payer_account_number', sa.String(length=32), nullable=True),
    sa.Column('payer_bank_name', sa.String(length=128), nullable=True),
    sa.Column('transaction_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_contributions_campaign_id_campaigns')),
    sa.ForeignKeyConstraint(['contributor_id'], ['users.id'], name=op.f('fk_contributions_contributor_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contributions'))
    )
    with op.batch_alter_table('contributions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contributions_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contributions_contributor_id'), ['contributor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contributions_kora_reference'), ['kora_reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_contributions_status'), ['status'], unique=False)

    op.create_table('ledger_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=24), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('reference', sa.String(length=64), nullable=True),
    sa.Column('source_type', sa.String(length=32), nullable=True),
    sa.Column('source_id', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_ledger_entries_campaign_id_campaigns')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_entries'))
    )
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ledger_entries_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_entries_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_entries_reference'), ['reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_entries_type'), ['type'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_notifications_campaign_id_campaigns')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_read'), ['read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('milestones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('beneficiary_id', sa.Integer(), nullable=True),
    sa.Column('trigger_type', sa.String(length=16), nullable=False),
    sa.Column('threshold_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('threshold_percentage', sa.Double(), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_milestones_approved_by_users')),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiaries.id'], name=op.f('fk_milestones_beneficiary_id_beneficiaries')),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_milestones_campaign_id_campaigns')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_milestones'))
    )
    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_milestones_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_milestones_status'), ['status'], unique=False)

    op.create_table('campaign_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('milestone_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_campaign_updates_campaign_id_campaigns')),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], name=op.f('fk_campaign_updates_milestone_id_milestones')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaign_updates'))
    )
    with op.batch_alter_table('campaign_updates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_updates_campaign_id'), ['campaign_id'], unique=False)

    op.create_table('payout_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('milestone_id', sa.Integer(), nullable=True),
    sa.Column('beneficiary_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('percentage', sa.Double(), nullable=True),
    sa.Column('trigger_type', sa.String(length=16), nullable=False),
    sa.Column('threshold_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('threshold_percentage', sa.Double(), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiaries.id'], name=op.f('fk_payout_rules_beneficiary_id_beneficiaries')),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_payout_rules_campaign_id_campaigns')),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], name=op.f('fk_payout_rules_milestone_id_milestones')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payout_rules'))
    )
    with op.batch_alter_table('payout_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payout_rules_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payout_rules_milestone_id'), ['milestone_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payout_rules_status'), ['status'], unique=False)

    op.create_table('payouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('beneficiary_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('milestone_id', sa.Integer(), nullable=True),
    sa.Column('kora_reference', sa.String(length=64), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_payouts_approved_by_users')),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiaries.id'], name=op.f('fk_payouts_beneficiary_id_beneficiaries')),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_payouts_campaign_id_campaigns')),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], name=op.f('fk_payouts_milestone_id_milestones')),
    sa.ForeignKeyConstraint(['rule_id'], ['payout_rules.id'], name=op.f('fk_payouts_rule_id_payout_rules')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payouts'))
    )
    with op.batch_alter_table('payouts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payouts_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payouts_kora_reference'), ['kora_reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_payouts_milestone_id'), ['milestone_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payouts_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payouts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payouts_status'))
        batch_op.drop_index(batch_op.f('ix_payouts_milestone_id'))
        batch_op.drop_index(batch_op.f('ix_payouts_kora_reference'))
        batch_op.drop_index(batch_op.f('ix_payouts_campaign_id'))

    op.drop_table('payouts')
    with op.batch_alter_table('payout_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payout_rules_status'))
        batch_op.drop_index(batch_op.f('ix_payout_rules_milestone_id'))
        batch_op.drop_index(batch_op.f('ix_payout_rules_campaign_id'))

    op.drop_table('payout_rules')
    with op.batch_alter_table('campaign_updates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_updates_campaign_id'))

    op.drop_table('campaign_updates')
    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_milestones_status'))
        batch_op.drop_index(batch_op.f('ix_milestones_campaign_id'))

    op.drop_table('milestones')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_read'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))
        batch_op.drop_index(batch_op.f('ix_notifications_campaign_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ledger_entries_type'))
        batch_op.drop_index(batch_op.f('ix_ledger_entries_reference'))
        batch_op.drop_index(batch_op.f('ix_ledger_entries_created_at'))
        batch_op.drop_index(batch_op.f('ix_ledger_entries_campaign_id'))

    op.drop_table('ledger_entries')
    with op.batch_alter_table('contributions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contributions_status'))
        batch_op.drop_index(batch_op.f('ix_contributions_kora_reference'))
        batch_op.drop_index(batch_op.f('ix_contributions_contributor_id'))
        batch_op.drop_index(batch_op.f('ix_contributions_campaign_id'))

    op.drop_table('contributions')
    with op.batch_alter_table('campaign_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_campaign_members_campaign_id'))

    op.drop_table('campaign_members')
    with op.batch_alter_table('campaign_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_accounts_kora_account_reference'))
        batch_op.drop_index(batch_op.f('ix_campaign_accounts_kora_account_number'))
        batch_op.drop_index(batch_op.f('ix_campaign_accounts_campaign_id'))

    op.drop_table('campaign_accounts')
    with op.batch_alter_table('beneficiaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_beneficiaries_campaign_id'))

    op.drop_table('beneficiaries')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_campaign_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_status'))
        batch_op.drop_index(batch_op.f('ix_campaigns_slug'))
        batch_op.drop_index(batch_op.f('ix_campaigns_owner_id'))

    op.drop_table('campaigns')
    with op.batch_alter_table('webhook_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_events_provider_reference'))
        batch_op.drop_index(batch_op.f('ix_webhook_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_webhook_events_created_at'))

    op.drop_table('webhook_events')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
